#!/usr/bin/bash
#
#

HEADER="Battery"
IS_ONLINE=/tmp/sb-battery-online
STATE=/tmp/sb-battery-state

touch $STATE
touch $IS_ONLINE

state=$(acpi -b | sed "s/^.*: //g; s/%.*$//g; s/,.*$//g")
percentage=$(acpi -b | sed "s/^.*: //g; s/%.*$//g; s/^.*, //g")
adapter=$(acpi -a | awk '/Adapter/ {print $3}')

[[ $percentage -lt 15 ]] && cat /dev/null > $STATE

info() {
  printf "%s" "$(acpi -iab | sed "s/^.*: //g; s/, /\n/g")"
}

first_timer() {
  [[ "$adapter" == "on-line" ]] && cat /dev/null > $STATE && echo 0 && return
  [[ -z "$(cat $STATE)" ]] && echo 1 && return
  [[ "$(cat $STATE)" == "$1" ]] && echo 0 || echo 1
}

notify() {
  case "$1" in
    35)
      [[ "$(first_timer 35)" == "1" ]] && notify-send -u low -c warn "$HEADER" \
        "We ran out of energy!"
      echo "35" > $STATE
      ;;
    25)
      [[ "$(first_timer 25)" == "1" ]] && notify-send -c warn "$HEADER" \
        "Come on! you have to do something, bro!"
      echo "25" > $STATE
      ;;
    15)
      [[ "$(first_timer 15)" == "1" ]] && notify-send -u critical -c warn "$HEADER" \
        "Tesla is upset with you!"
      echo "15" > $STATE
      ;;
    "con")
      local urgancy
      if [[ "$adapter" == "off-line" ]]; then
        urgancy="critical"
      else
        urgancy="low"
      fi
      notify-send -u "$urgancy" "$HEADER" \
        "Adapter goes $adapter"
      ;;
    "info")
      notify-send "$HEADER" \
        "$(info)"
      ;;
  esac
}

if [[ "$(cat $IS_ONLINE)" != "$adapter" ]]; then
  echo "$adapter" > $IS_ONLINE
  notify "con"
fi

notify "$percentage"

case "${state}" in
  "Discharging") status="" ;;
  "Charging") status="" ;;
  "Not charging") status="ﮤ" ;;
  "Unknown") status="ﳠ" ;;
  "Full") status="" ;;
  "")
    status=""
    percentage="AC"
    ;;
esac

[[ "$adapter" == "of-line" ]] && [[ "${percentage}" -le 15 ]] && status=""
[[ "${percentage}" != "AC" ]] && percentage="${percentage}%"

printf "%s" "$status $percentage"

case ${BUTTON} in
  1) notify "info" ;;
esac
