#!/usr/bin/bash
#
# Author: Abd El-Twab M. Fakhry
# Description: Show CPU usage
# License: GPLv3+

CPU_ICON=""
utilization=$(sar -u 1 1 | awk 'FNR == 5 { printf "%02.00f", (100.0 - $8) }')

echo -e "$CPU_ICON $utilization%"

top_cpu_usage() {
  printf "%s" "$(ps axch -o %cpu,cmd --sort=-%cpu | sed 11q |
    awk 'BEGIN { printf "%-30s %s\n", "Process:", "Usage:";
      printf "%-30s %s\n", "--------", "------" }
      { printf "%-30s %s\n", $2, $1 "%" }')"
}

case ${BUTTON} in
  1)
    notify-send -u critical "Top 10 CPU Processes" "$(top_cpu_usage)"
    ;;
esac
