#!/usr/bin/bash
#
# Author: Abd El-Twab M. Fakhry
# Description: Display current keyboard layout
# License: GPLv3+

LANG_ICON=""

get_layout() {
  local layout
  local lang
  layout=$(setxkbmap -query | tr , ' ' | awk 'FNR == 3 {print $2}')

  case "${layout}" in
    ar) lang="ar" ;;
    us) lang="us" ;;
    *)
      # Force toggle to US_en
      set-keyboard-layout "us"
      lang="us"
      ;;
  esac

  printf "%s" "${lang}"
}

echo "$LANG_ICON $(get_layout)"

case "${BUTTON}" in
  1) set-keyboard-layout ;;
esac
