#!/bin/bash
#
# Displays count of unread inbox and spam mails.

ICON=""
work_inbox_new=$(find "${XDG_DATA_HOME:-$HOME/.local/share}"/Mail/work/Inbox/new/* -type f 2>/dev/null | wc -l)
work_spam_new=$(find "${XDG_DATA_HOME:-$HOME/.local/share}"/Mail/work/\[Gmail\]/Spam/new/* -type f 2>/dev/null | wc -l)

azhar_inbox_new=$(find "${XDG_DATA_HOME:-$HOME/.local/share}"/Mail/azhar/Inbox/new/* -type f 2>/dev/null | wc -l)
azhar_spam_new=$(find "${XDG_DATA_HOME:-$HOME/.local/share}"/Mail/azhar/Spambox/new/* -type f 2>/dev/null | wc -l)

unread=$((work_inbox_new + work_spam_new + azhar_inbox_new + azhar_spam_new))

# Notify on new mails
mailnotify

echo "${ICON} ${unread}"

case "${BUTTON}" in
  1) setsid -f "${TERMINAL}" -e neomutt ;;
esac
