#!/usr/bin/bash
#
# Author: Abd El-Twab M. Fakhry
# Description: Show Memory usage
# License: GPLv3+

MEMORY_ICON=""
precentage=$(free -m | awk 'FNR == 2 {printf "%02.00f\n", (($2 - $7) / $2 * 100)}')

echo -e "${MEMORY_ICON} ${precentage}%"

top_memory_usage() {
  printf "%s" "$(ps axch -o %mem,cmd --sort=-%mem | sed 11q |
    awk 'BEGIN { printf "%-20s %s\n", "Process:", "Usage:";
          printf "%-20s %s\n", "--------", "------" }
          { printf "%-20s %s\n", $2, $1 "%" }')"
}

case ${BUTTON} in
  1)
    notify-send -u critical "Top 10 Memory Porcesses" "$(top_memory_usage)"
    ;;
esac
