#!/usr/bin/bash
#
# Display how many packages need approval to be update

PACKAGE_ICON=""
CACHE_FILE="$HOME/.cache/pacups.packages"
packages=$(sudo pacman -Qu | grep -Fcv "[ignored]")

if ((packages >= 10));
then
  packages="+9"
fi

echo -e "${PACKAGE_ICON} ${packages}"

case ${BUTTON} in
  1) echo sudo pacman -Su > "$CACHE_FILE" && sudo pacman -Qu >> "$CACHE_FILE" ;
    choice=$(cat "$HOME"/.cache/pacups.packages | dmenu -p "Upgraded packages:" -l 15) \
    && [[ "$choice" == "sudo pacman -Su" ]] \
    && setsid "$TERMINAL" -e sudo pacman -Su \
    && exit
    ;;
esac
