#!/usr/bin/bash
#
# Description: Display how many packages need approval to be update

CACHE_FILE="$HOME/.cache/pacups.packages"
PACKAGE_ICON=""

packages=$(sudo pacman -Qu | grep -Fcv "[ignored]")

if ((packages > 99)); then
  packages="+99"
fi

show_packages() {
  sudo pacman -Qu > "$CACHE_FILE"
  choice=$(cat "$CACHE_FILE" | awk '{printf "%-60s%-10s%-4s%s\n", $1, $2, $3, $4}' | dmenu -p "Available upgrades" -l 15)
  [[ -n "$choice" ]] && setsid "$TERMINAL" -e sudo pacman -Su --noconfirm
}

printf "%s" "${PACKAGE_ICON} ${packages}"

case ${BUTTON} in
  1) show_packages ;;
esac
