#!/usr/bin/bash
#
#
#

ICON_FILE=/tmp/recordingicon
RECORD_ICON=""

[[ -n "$(cat $ICON_FILE)" ]] && RECORD_ICON="$(cat $ICON_FILE)"

printf "%s" "${RECORD_ICON}"

case ${BUTTON} in
  1) dmenu_record ;;
esac
