#!/usr/bin/bash
#
#
#

ICON_FILE=/tmp/recordingicon
touch $ICON_FILE
RECORD_ICON=""

[[ -z "$(cat $ICON_FILE)" ]] && echo "$RECORD_ICON" > "$ICON_FILE"

printf "%s" "${RECORD_ICON}"

case ${BUTTON} in
  1) dmenu_record ;;
esac
