#!/bin/bash

volume_up="🔊"
volume_down="🔉"
volume_off="🔇"

volume_percentage=$(pamixer --get-volume)
is_muted=$(pamixer --get-mute)

# -eg -> equal
# -lt -> lessthan
# -gt -> greaterthan

if [[ "$is_muted" == "true" ]] || [[ "$volume_percentage" == "0" ]]; then
  ICON=${volume_off}
  # ${word/pattern/replacement}
elif [[ "${volume_percentage//%/}" -lt 50 ]]; then
  ICON=${volume_down}
else
  ICON=${volume_up}
fi

echo -e "${ICON} ${volume_percentage}%"

case ${BUTTON} in
  1) setsid pavucontrol ;;
esac
