#!/usr/bin/bash
#
#
#

volume_up=""
volume_down=""
volume_mid="墳"
volume_off="婢"
volume_mute="ﱝ"

percentage=$(pamixer --get-volume)
is_muted=$(pamixer --get-mute)

# -eg -> equal
# -lt -> lessthan
# -gt -> greaterthan

if [[ "$is_muted" == "true" ]]; then
  ICON=${volume_mute}
elif [[ "$percentage" == "0" ]]; then
  ICON=${volume_off}
  # ${word/pattern/replacement}
elif [[ "${percentage//%/}" -lt 33 ]]; then
  ICON=${volume_down}
elif [[ "${percentage//%/}" -lt 66 ]]; then
  ICON=${volume_mid}
else
  ICON=${volume_up}
fi

echo -e "${ICON} ${percentage}%"

case ${BUTTON} in
  1) setsid pavucontrol ;;
esac
