#!/usr/bin/bash
#
# Callable script every 0, 50 minutes

export DBUS_SESSION_BUS_ADDRESS
DBUS_SESSION_BUS_ADDRESS=$(cat /tmp/dbus-current-session)

message_body() {
  if [[ "$(date "+%M")" -eq "50" ]]; then
    echo "<b><span color=\"white\">You've done a great job</span></b> ✅"
    echo "Time to take a <b><span color=\"green\">break</span></b> 😌"
  else
    echo "A new session has begun"
    echo "You have <b><span color=\"white\">50 minutes</span></b> to achieve something valuable 🤓"
  fi
}

notify-send "⏰ Pomodoro Cronie" "$(message_body)"
