#!/usr/bin/bash
#
# Author: Abd El-Twab M. Fakhry
# Description: Sync mails with different mail providers

export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"

export DBUS_SESSION_BUS_ADDRESS
DBUS_SESSION_BUS_ADDRESS=$(cat /tmp/dbus-current-session)

export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

/usr/bin/mbsync -ac "${XDG_CONFIG_HOME:-$HOME/.config}/isync/mbsyncrc"

# Notify new mails
"$HOME"/.local/sbin/cronie/cr-notify-new-mail
