#!/usr/bin/bash
#
#
# Description: Decrypt given file or directory

OBJECT="$1"
OUTPUT_DIR="$2"

decrypted_file_name="${OBJECT/.gpg/}"

_test() {
  [[ -z "$OBJECT" ]] && echo "No such a file or directory!" && exit 1
  [[ -z "$OUTPUT_DIR" ]] && OUTPUT_DIR="."
}

_decrypt() {
  gpg -d "$OUTPUT_DIR/$OBJECT" > "$OUTPUT_DIR/${decrypted_file_name:?}"
}

_dearchive() {
  7za x -so "$OUTPUT_DIR/${decrypted_file_name:?}" | tar xpzPf -
}

_clean() {
  rm -rf "$OUTPUT_DIR/${decrypted_file_name:?}"
}

main() {
  _test
  _decrypt
  _dearchive
  _clean
}

main
