#!/usr/bin/bash
#
# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

# If no url given. Opens browser. For using script as $BROWSER.
[[ -z "$1" ]] && {
  "$BROWSER"
  exit
}

case "$1" in
  *mkv | *webm | *mp4 | *youtu.*be* | *mp3 | *ogg | *wav)
    setsid -f mpv --ytdl-format=22 -quiet "$1" > /dev/null 2>&1
    ;;
  *png | *jpg | *jpe | *jpeg | *gif)
    curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" &&
      sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" > /dev/null 2>&1 &
    ;;
  *pdf | *cbz | *cbr | *djvu | *epub)
    curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" &&
      zathura "/tmp/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" > /dev/null 2>&1 &
    ;;
  *)
    if [[ -f "$1" ]]; then
      setsid -f "$TERMINAL" -e "$EDITOR" "$1" > /dev/null 2>&1
    else
      setsid -f "$BROWSER" "$1" > /dev/null 2>&1
    fi
    ;;
esac
