#!/usr/bin/bash
#
# This script is meant to be search engine for fonts.

notify() {
    notify-send " Copied to clipboard" "$1"
}

search_font() {
    local font_info
    font_info=$(fc-list | awk -F: '{printf "%-60s # %-30s # %s\n", $2, $3, $1}' | dmenu -l 15 -p "Search font: ")

    font_name=$(echo "$font_info" | awk -F# '{print $1}' | xargs)
    font_path=$(echo "$font_info" | awk -F# '{print $3}' | xargs)

    if [ -z "$font_name" ]; then
        exit 1
    fi

    choice=$(printf "Name\nPath" | dmenu -p "Copy to clipboard: ")
    if [ "$choice" = "Name" ]; then
        xclip -selection clipboard -i <<< "$font_name" | notify "$font_name"
    elif [ "$choice" = "Path" ]; then
        xclip -selection clipboard -i <<< "$font_path" | notify "$font_path"
    fi
}

search_font
