#!/usr/bin/bash
#
#

update_sb() {
  pkill -RTMIN+5 dwmblocks
}

value="$2"
[[ -z "${value}" ]] && value=3

case "$1" in
  up)
    xbacklight -time 200 -inc ${value}
    ;;
  down)
    xbacklight -time 200 -dec ${value}
    ;;
  set)
    xbacklight -time 200 -set ${value}
    ;;
esac

update_sb
