#!/bin/bash
#
# Notify with the number of new messages whenever mail has been retrieved.

readonly MAIL_PREFIX="$HOME/.local/share/Mail/"

declare -a locations=(
	"work/Inbox/new"
	"work/[Gmail]/Spam/new"
	"azhar/Inbox/new"
	"azhar/Spambox/new"
)

declare -a messages_time=()
for ((i = 0; i < ${#locations[@]}; ++i)); do
	tmp=($(ls ${MAIL_PREFIX}"${locations[i]}" | awk -F. '{print $1}'))

	for ((j = 0; j < ${#tmp[@]}; ++j)); do
		messages_time+=("${tmp[j]}")
	done
done

IFS=$'\n' sorted=($(sort -h <<<"${messages_time[*]}"))
unset IFS

notify() {
	notify-send "You have $1 new mail(s)" -t 10000
}

search() {
	local low=0
	local high=${#sorted[@]}
	local unix_time
	unix_time=$(($1 - 25))
	local answer=-1

	while ((low < high)); do
		mid=$(((low + high) / 2))
		if (( sorted[mid] >= unix_time )); then
			high=$((mid))
			answer=$((mid))
		else
			low=$((mid + 1))
		fi
	done

	if (( answer < 0 )); then
		exit 0
	else
		local new
		new=$((${#sorted[@]} - answer))
		notify "${new}"
	fi
}

search "$(date '+%s')"
