#!/usr/bin/bash

PREFIX="$HOME/.local/share/quotes/ar/"
TMP_QUOTE=/tmp/quote-ar

export DBUS_SESSION_BUS_ADDRESS
DBUS_SESSION_BUS_ADDRESS=$(cat /tmp/dbus-current-session)

cp "$(find "$PREFIX" -name "*.txt" | shuf -n 1)" "$TMP_QUOTE"

notify-send "حكمة اليوم" "$(cat "$TMP_QUOTE")"
