#!/usr/bin/env bash

shopt -s nullglob globstar

if [[ -n $DISPLAY ]]; then
	dmenu=dmenu
else
	echo "Error: No X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR:-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@" -l 15 -p "Pass: ")

[[ -n $password ]] || exit

flag="pw"
otp_regex='(otp)'

[[ "$password" =~ $otp_regex ]] && flag="otp"

if [[ "$flag" == "otp" ]]; then
	pass otp show -c "$password"
else
	pass show -c "$password"
fi
